global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "prometheus"

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
      - targets: ["localhost:9090"]
      
  - job_name: "fastapi_app"
    static_configs:
      - targets: ["localhost:8000"]

  - job_name: "bento_model"
    static_configs:
      - targets: ["localhost:4000"]